import {defineApp,feature} from './domain-config.mjs';
export default defineApp({
  "id": "ai-payment-processor-fee-settlement-audit",
  "engine": "recovery",
  "title": "Payment Processor Fee & Settlement Audit",
  "shortTitle": "Payment Processor Fee and Settlement Audit",
  "tagline": "Find processor pricing, reserve, and settlement errors and reconcile transaction-level cash to contractual economics.",
  "industry": "Payments Financial Operations",
  "buyer": "Enterprise merchants and platforms",
  "uiPort": 4668,
  "apiPort": 5668,
  "accent": "#4338ca",
  "currency": "USD",
  "primaryOutcome": "Payment Processor Fee & Settlement Audit converted into governed, evidence-backed financial outcomes",
  "valueNarrative": "Connect processing agreements, transaction logs, authorizations, captures, refunds, chargebacks, pricing tiers, gateway fees, reserves, settlements, and bank deposits in one accountable workflow. Find processor pricing, reserve, and settlement errors and reconcile transaction-level cash to contractual economics.",
  "calculation": {
    "actualKey": "chargedAmount",
    "expectedKey": "supportedAmount",
    "actualLabel": "Charged or Paid Amount",
    "expectedLabel": "Evidence-Supported Amount",
    "varianceLabel": "Potential recovery or avoided cost",
    "direction": "actual-minus-expected",
    "finding": "Payment Processor Fee & Settlement Audit evidence indicates a measurable financial exception.",
    "actions": [
      "Validate the effective agreement, eligibility rules, and accountable parties",
      "Reconcile transaction-level operational and financial evidence",
      "Prepare the correction, recovery, or compliance package",
      "Track counterparty response, approval, cash, and preventive control closure"
    ]
  }
},[
feature("processor-agreement-library","PPF01","Processor agreement library","Execute processor agreement library using processing agreements, transaction logs, authorizations, captures, refunds, chargebacks, pricing tiers, gateway fees, reserves, settlements, and bank deposits.","Produce a governed processor agreement library decision with quantified value, accountable ownership, retained evidence, and measurable closure.",[["caseEntity","Processor / Merchant Account","text","Processor / Merchant Account · Standard Case"],["caseReference","Processor agreement library Reference","text","PPF01-2026-001"],["chargedAmount","Charged or Paid Amount","currency",851250],["supportedAmount","Evidence-Supported Amount","currency",715050],["domainDriver","Pricing Model","select","Interchange plus",["Interchange plus","Blended","Flat rate"]],["evidenceState","Evidence State","select","Complete",["Complete","Incomplete","Exception"]],["reviewDeadline","Review Deadline","date","2026-10-31"]],{amountField:"chargedAmount",subjects:["Processor agreement library case","Merchant account registry case","Authorization capture ingestion case","Refund chargeback ingestion case","Pricing model reconstruction case"]}),
feature("merchant-account-registry","PPF02","Merchant account registry","Execute merchant account registry using processing agreements, transaction logs, authorizations, captures, refunds, chargebacks, pricing tiers, gateway fees, reserves, settlements, and bank deposits.","Produce a governed merchant account registry decision with quantified value, accountable ownership, retained evidence, and measurable closure.",[["caseEntity","Processor / Merchant Account","text","Processor / Merchant Account · Standard Case"],["caseReference","Merchant account registry Reference","text","PPF02-2026-001"],["chargedAmount","Charged or Paid Amount","currency",851250],["supportedAmount","Evidence-Supported Amount","currency",715050],["domainDriver","Pricing Model","select","Interchange plus",["Interchange plus","Blended","Flat rate"]],["evidenceState","Evidence State","select","Complete",["Complete","Incomplete","Exception"]],["reviewDeadline","Review Deadline","date","2026-10-31"]],{amountField:"chargedAmount",subjects:["Processor agreement library case","Merchant account registry case","Authorization capture ingestion case","Refund chargeback ingestion case","Pricing model reconstruction case"]}),
feature("authorization-capture-ingestion","PPF03","Authorization capture ingestion","Execute authorization capture ingestion using processing agreements, transaction logs, authorizations, captures, refunds, chargebacks, pricing tiers, gateway fees, reserves, settlements, and bank deposits.","Produce a governed authorization capture ingestion decision with quantified value, accountable ownership, retained evidence, and measurable closure.",[["caseEntity","Processor / Merchant Account","text","Processor / Merchant Account · Standard Case"],["caseReference","Authorization capture ingestion Reference","text","PPF03-2026-001"],["chargedAmount","Charged or Paid Amount","currency",851250],["supportedAmount","Evidence-Supported Amount","currency",715050],["domainDriver","Pricing Model","select","Interchange plus",["Interchange plus","Blended","Flat rate"]],["evidenceState","Evidence State","select","Complete",["Complete","Incomplete","Exception"]],["reviewDeadline","Review Deadline","date","2026-10-31"]],{amountField:"chargedAmount",subjects:["Processor agreement library case","Merchant account registry case","Authorization capture ingestion case","Refund chargeback ingestion case","Pricing model reconstruction case"]}),
feature("refund-chargeback-ingestion","PPF04","Refund chargeback ingestion","Execute refund chargeback ingestion using processing agreements, transaction logs, authorizations, captures, refunds, chargebacks, pricing tiers, gateway fees, reserves, settlements, and bank deposits.","Produce a governed refund chargeback ingestion decision with quantified value, accountable ownership, retained evidence, and measurable closure.",[["caseEntity","Processor / Merchant Account","text","Processor / Merchant Account · Standard Case"],["caseReference","Refund chargeback ingestion Reference","text","PPF04-2026-001"],["chargedAmount","Charged or Paid Amount","currency",851250],["supportedAmount","Evidence-Supported Amount","currency",715050],["domainDriver","Pricing Model","select","Interchange plus",["Interchange plus","Blended","Flat rate"]],["evidenceState","Evidence State","select","Complete",["Complete","Incomplete","Exception"]],["reviewDeadline","Review Deadline","date","2026-10-31"]],{amountField:"chargedAmount",subjects:["Processor agreement library case","Merchant account registry case","Authorization capture ingestion case","Refund chargeback ingestion case","Pricing model reconstruction case"]}),
feature("pricing-model-reconstruction","PPF05","Pricing model reconstruction","Execute pricing model reconstruction using processing agreements, transaction logs, authorizations, captures, refunds, chargebacks, pricing tiers, gateway fees, reserves, settlements, and bank deposits.","Produce a governed pricing model reconstruction decision with quantified value, accountable ownership, retained evidence, and measurable closure.",[["caseEntity","Processor / Merchant Account","text","Processor / Merchant Account · Standard Case"],["caseReference","Pricing model reconstruction Reference","text","PPF05-2026-001"],["chargedAmount","Charged or Paid Amount","currency",851250],["supportedAmount","Evidence-Supported Amount","currency",715050],["domainDriver","Pricing Model","select","Interchange plus",["Interchange plus","Blended","Flat rate"]],["evidenceState","Evidence State","select","Complete",["Complete","Incomplete","Exception"]],["reviewDeadline","Review Deadline","date","2026-10-31"]],{amountField:"chargedAmount",subjects:["Processor agreement library case","Merchant account registry case","Authorization capture ingestion case","Refund chargeback ingestion case","Pricing model reconstruction case"]}),
feature("markup-fee-calculation","PPF06","Markup fee calculation","Execute markup fee calculation using processing agreements, transaction logs, authorizations, captures, refunds, chargebacks, pricing tiers, gateway fees, reserves, settlements, and bank deposits.","Produce a governed markup fee calculation decision with quantified value, accountable ownership, retained evidence, and measurable closure.",[["caseEntity","Processor / Merchant Account","text","Processor / Merchant Account · Standard Case"],["caseReference","Markup fee calculation Reference","text","PPF06-2026-001"],["chargedAmount","Charged or Paid Amount","currency",851250],["supportedAmount","Evidence-Supported Amount","currency",715050],["domainDriver","Pricing Model","select","Interchange plus",["Interchange plus","Blended","Flat rate"]],["evidenceState","Evidence State","select","Complete",["Complete","Incomplete","Exception"]],["reviewDeadline","Review Deadline","date","2026-10-31"]],{amountField:"chargedAmount",subjects:["Processor agreement library case","Merchant account registry case","Authorization capture ingestion case","Refund chargeback ingestion case","Pricing model reconstruction case"]}),
feature("gateway-fee-validation","PPF07","Gateway fee validation","Execute gateway fee validation using processing agreements, transaction logs, authorizations, captures, refunds, chargebacks, pricing tiers, gateway fees, reserves, settlements, and bank deposits.","Produce a governed gateway fee validation decision with quantified value, accountable ownership, retained evidence, and measurable closure.",[["caseEntity","Processor / Merchant Account","text","Processor / Merchant Account · Standard Case"],["caseReference","Gateway fee validation Reference","text","PPF07-2026-001"],["chargedAmount","Charged or Paid Amount","currency",851250],["supportedAmount","Evidence-Supported Amount","currency",715050],["domainDriver","Pricing Model","select","Interchange plus",["Interchange plus","Blended","Flat rate"]],["evidenceState","Evidence State","select","Complete",["Complete","Incomplete","Exception"]],["reviewDeadline","Review Deadline","date","2026-10-31"]],{amountField:"chargedAmount",subjects:["Processor agreement library case","Merchant account registry case","Authorization capture ingestion case","Refund chargeback ingestion case","Pricing model reconstruction case"]}),
feature("minimum-fee-control","PPF08","Minimum fee control","Execute minimum fee control using processing agreements, transaction logs, authorizations, captures, refunds, chargebacks, pricing tiers, gateway fees, reserves, settlements, and bank deposits.","Produce a governed minimum fee control decision with quantified value, accountable ownership, retained evidence, and measurable closure.",[["caseEntity","Processor / Merchant Account","text","Processor / Merchant Account · Standard Case"],["caseReference","Minimum fee control Reference","text","PPF08-2026-001"],["chargedAmount","Charged or Paid Amount","currency",851250],["supportedAmount","Evidence-Supported Amount","currency",715050],["domainDriver","Pricing Model","select","Interchange plus",["Interchange plus","Blended","Flat rate"]],["evidenceState","Evidence State","select","Complete",["Complete","Incomplete","Exception"]],["reviewDeadline","Review Deadline","date","2026-10-31"]],{amountField:"chargedAmount",subjects:["Processor agreement library case","Merchant account registry case","Authorization capture ingestion case","Refund chargeback ingestion case","Pricing model reconstruction case"]}),
feature("reserve-holdback-reconciliation","PPF09","Reserve holdback reconciliation","Execute reserve holdback reconciliation using processing agreements, transaction logs, authorizations, captures, refunds, chargebacks, pricing tiers, gateway fees, reserves, settlements, and bank deposits.","Produce a governed reserve holdback reconciliation decision with quantified value, accountable ownership, retained evidence, and measurable closure.",[["caseEntity","Processor / Merchant Account","text","Processor / Merchant Account · Standard Case"],["caseReference","Reserve holdback reconciliation Reference","text","PPF09-2026-001"],["chargedAmount","Charged or Paid Amount","currency",851250],["supportedAmount","Evidence-Supported Amount","currency",715050],["domainDriver","Pricing Model","select","Interchange plus",["Interchange plus","Blended","Flat rate"]],["evidenceState","Evidence State","select","Complete",["Complete","Incomplete","Exception"]],["reviewDeadline","Review Deadline","date","2026-10-31"]],{amountField:"chargedAmount",subjects:["Processor agreement library case","Merchant account registry case","Authorization capture ingestion case","Refund chargeback ingestion case","Pricing model reconstruction case"]}),
feature("settlement-timing-audit","PPF10","Settlement timing audit","Execute settlement timing audit using processing agreements, transaction logs, authorizations, captures, refunds, chargebacks, pricing tiers, gateway fees, reserves, settlements, and bank deposits.","Produce a governed settlement timing audit decision with quantified value, accountable ownership, retained evidence, and measurable closure.",[["caseEntity","Processor / Merchant Account","text","Processor / Merchant Account · Standard Case"],["caseReference","Settlement timing audit Reference","text","PPF10-2026-001"],["chargedAmount","Charged or Paid Amount","currency",851250],["supportedAmount","Evidence-Supported Amount","currency",715050],["domainDriver","Pricing Model","select","Interchange plus",["Interchange plus","Blended","Flat rate"]],["evidenceState","Evidence State","select","Complete",["Complete","Incomplete","Exception"]],["reviewDeadline","Review Deadline","date","2026-10-31"]],{amountField:"chargedAmount",subjects:["Processor agreement library case","Merchant account registry case","Authorization capture ingestion case","Refund chargeback ingestion case","Pricing model reconstruction case"]}),
feature("deposit-to-batch-matching","PPF11","Deposit-to-batch matching","Execute deposit-to-batch matching using processing agreements, transaction logs, authorizations, captures, refunds, chargebacks, pricing tiers, gateway fees, reserves, settlements, and bank deposits.","Produce a governed deposit-to-batch matching decision with quantified value, accountable ownership, retained evidence, and measurable closure.",[["caseEntity","Processor / Merchant Account","text","Processor / Merchant Account · Standard Case"],["caseReference","Deposit-to-batch matching Reference","text","PPF11-2026-001"],["chargedAmount","Charged or Paid Amount","currency",851250],["supportedAmount","Evidence-Supported Amount","currency",715050],["domainDriver","Pricing Model","select","Interchange plus",["Interchange plus","Blended","Flat rate"]],["evidenceState","Evidence State","select","Complete",["Complete","Incomplete","Exception"]],["reviewDeadline","Review Deadline","date","2026-10-31"]],{amountField:"chargedAmount",subjects:["Processor agreement library case","Merchant account registry case","Authorization capture ingestion case","Refund chargeback ingestion case","Pricing model reconstruction case"]}),
feature("missing-settlement-detection","PPF12","Missing settlement detection","Execute missing settlement detection using processing agreements, transaction logs, authorizations, captures, refunds, chargebacks, pricing tiers, gateway fees, reserves, settlements, and bank deposits.","Produce a governed missing settlement detection decision with quantified value, accountable ownership, retained evidence, and measurable closure.",[["caseEntity","Processor / Merchant Account","text","Processor / Merchant Account · Standard Case"],["caseReference","Missing settlement detection Reference","text","PPF12-2026-001"],["chargedAmount","Charged or Paid Amount","currency",851250],["supportedAmount","Evidence-Supported Amount","currency",715050],["domainDriver","Pricing Model","select","Interchange plus",["Interchange plus","Blended","Flat rate"]],["evidenceState","Evidence State","select","Complete",["Complete","Incomplete","Exception"]],["reviewDeadline","Review Deadline","date","2026-10-31"]],{amountField:"chargedAmount",subjects:["Processor agreement library case","Merchant account registry case","Authorization capture ingestion case","Refund chargeback ingestion case","Pricing model reconstruction case"]}),
feature("processor-dispute-workflow","PPF13","Processor dispute workflow","Execute processor dispute workflow using processing agreements, transaction logs, authorizations, captures, refunds, chargebacks, pricing tiers, gateway fees, reserves, settlements, and bank deposits.","Produce a governed processor dispute workflow decision with quantified value, accountable ownership, retained evidence, and measurable closure.",[["caseEntity","Processor / Merchant Account","text","Processor / Merchant Account · Standard Case"],["caseReference","Processor dispute workflow Reference","text","PPF13-2026-001"],["chargedAmount","Charged or Paid Amount","currency",851250],["supportedAmount","Evidence-Supported Amount","currency",715050],["domainDriver","Pricing Model","select","Interchange plus",["Interchange plus","Blended","Flat rate"]],["evidenceState","Evidence State","select","Complete",["Complete","Incomplete","Exception"]],["reviewDeadline","Review Deadline","date","2026-10-31"]],{amountField:"chargedAmount",subjects:["Processor agreement library case","Merchant account registry case","Authorization capture ingestion case","Refund chargeback ingestion case","Pricing model reconstruction case"]}),
feature("cash-recovery-ledger","PPF14","Cash recovery ledger","Execute cash recovery ledger using processing agreements, transaction logs, authorizations, captures, refunds, chargebacks, pricing tiers, gateway fees, reserves, settlements, and bank deposits.","Produce a governed cash recovery ledger decision with quantified value, accountable ownership, retained evidence, and measurable closure.",[["caseEntity","Processor / Merchant Account","text","Processor / Merchant Account · Standard Case"],["caseReference","Cash recovery ledger Reference","text","PPF14-2026-001"],["chargedAmount","Charged or Paid Amount","currency",851250],["supportedAmount","Evidence-Supported Amount","currency",715050],["domainDriver","Pricing Model","select","Interchange plus",["Interchange plus","Blended","Flat rate"]],["evidenceState","Evidence State","select","Complete",["Complete","Incomplete","Exception"]],["reviewDeadline","Review Deadline","date","2026-10-31"]],{amountField:"chargedAmount",subjects:["Processor agreement library case","Merchant account registry case","Authorization capture ingestion case","Refund chargeback ingestion case","Pricing model reconstruction case"]}),
feature("account-processor-analytics","PPF15","Account processor analytics","Execute account processor analytics using processing agreements, transaction logs, authorizations, captures, refunds, chargebacks, pricing tiers, gateway fees, reserves, settlements, and bank deposits.","Produce a governed account processor analytics decision with quantified value, accountable ownership, retained evidence, and measurable closure.",[["caseEntity","Processor / Merchant Account","text","Processor / Merchant Account · Standard Case"],["caseReference","Account processor analytics Reference","text","PPF15-2026-001"],["chargedAmount","Charged or Paid Amount","currency",851250],["supportedAmount","Evidence-Supported Amount","currency",715050],["domainDriver","Pricing Model","select","Interchange plus",["Interchange plus","Blended","Flat rate"]],["evidenceState","Evidence State","select","Complete",["Complete","Incomplete","Exception"]],["reviewDeadline","Review Deadline","date","2026-10-31"]],{amountField:"chargedAmount",subjects:["Processor agreement library case","Merchant account registry case","Authorization capture ingestion case","Refund chargeback ingestion case","Pricing model reconstruction case"]})
]);
